name: Aprendiendo Github Actions
run-name: learning_github_actions
on: [push]
jobs: 
  hola-mundo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
      - name: Definir variable de entorno
        uses: echo "USERNAME={{ github.actor }}">> $GITHUB_ENV
      - name: Correr script
        run: python hola_mundo.py